#!/bin/sh


[[ -z $1 ]] && exit 1

ICON="/home/aiffelowy/.config/nixos/home/aiffelowy/dotfiles/assets/dunst/assets/notification/speaker.png"

brightnessctl set 5%"${1}"

BRIGHT=$(brightnessctl -m i | awk -F ',' '{print $4}' | tr -d "%")
BRIGHT_BAR=

for ((i = 1; i <= 10; i++)); do
  SYMBOL="█"
  [[ $(($i*10)) -gt $BRIGHT ]] && SYMBOL="_"
  BRIGHT_BAR="${BRIGHT_BAR}${SYMBOL}"
done


notify-send -u low -i $ICON -a Brightnessctl -h int:transient:1 -h string:x-canonical-private-synchronous:anything -t 1500 "Brightness Changed" "$BRIGHT_BAR [${BRIGHT}%]"
