#!/bin/sh

[[ -z $1 ]] && exit 1

ICON="$HOME/.config/nixos/home/shared/dotfiles/assets/dunst/assets/notification/speaker.png"

amixer -q set Master 5%"${1}"

VOL=$(amixer get Master | awk '/Left:/ {print $6=="[off]"?$6:$5}' | tr -d '[]%')
VOL_BAR=


for ((i = 1; i <= 10; i++)); do
  SYMBOL="█"
  echo $VOL
  [[ $(($i*10)) -gt $VOL ]] && SYMBOL="_"
  VOL_BAR="${VOL_BAR}${SYMBOL}"
done

notify-send -u low -i $ICON -a Amixer -h int:transient:1 -h string:x-canonical-private-synchronous:anything -t 1500 "Volume Changed" "$VOL_BAR [${VOL}%]"
